### ISSUE TITLE
mixin 使用问题

### ISSUE THREAD

**Issue by sosky-yty** [HxBreak/new_trend#2]
error: The class 'BaseModel' can't be used as a mixin because it extends a class other than Object. (mixin_inherits_from_not_object at [new_trend] lib/models/main_state_model.dart:20)
error: The class 'IndexScreenStateModel' can't be used as a mixin because it extends a class other than Object. (mixin_inherits_from_not_object at [new_trend] lib/models/main_state_model.dart:21)
error: The class 'BasicScreenStateModel' can't be used as a mixin because it extends a class other than Object. (mixin_inherits_from_not_object at [new_trend] lib/models/main_state_model.dart:22)
error: The class 'UserAuthModel' can't be used as a mixin because it extends a class other than Object. (mixin_inherits_from_not_object at [new_trend] lib/models/main_state_model.dart:23)
error: The class 'TasksStateModel' can't be used as a mixin because it extends a class other than Object. (mixin_inherits_from_not_object at [new_trend] lib/models/main_state_model.dart:24)

**Comment by HxBreak** [comment]
五一假期内修复

**Comment by HxBreak** [comment]
fix #1 查看最新commit内容

**Comment by HxBreak** [comment]
晚了四十分钟
